language: python
sudo: false
dist: bionic

cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

env:
  matrix:
   - ''  # main tests

before_install:
  - pip install -e git+https://github.com/openwisp/django-ipam#egg=django-ipam
  - pip install --no-cache-dir -U -r requirements-test.txt

install:
  - pip install "django>=2.0,<2.1"
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=openwisp_ipam runtests.py
  - >
    openwisp-utils-qa-checks \
        --migration-path ./openwisp_ipam/migrations/ \
        --migration-module openwisp_ipam

after_success:
  - coveralls
