language: python
dist: bionic

cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

env:
  - DJANGO="django>=2.2,<2.3"
  - DJANGO="django>=3.0,<3.1"

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt

install:
  - pip install $DJANGO
  - python setup.py -q develop
  - npm install -g jslint

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_ipam runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  - coveralls
