#!/bin/bash
set -e

coverage erase

coverage run runtests.py --parallel --exclude-tag=selenium_tests

SELENIUM_HEADLESS=1 coverage run runtests.py --tag=selenium_tests --no-input

SAMPLE_APP=1 coverage run runtests.py --parallel --exclude-tag=selenium_tests

coverage combine
coverage xml
