# Generated by Django 5.2.13 on 2026-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authtoken", "0001_initial"),
        ("sample_users", "0002_default_groups_and_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="If set, the account will be deactivated after this date passes and the user will no longer be able to log in.",
                null=True,
                verbose_name="expiration date",
            ),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authtoken.token",),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "expiration_date"], name="user_active_expiry_idx"
            ),
        ),
    ]
