# Generated by Django 4.2.4 on 2023-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_users", "0002_default_groups_and_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_updated",
            field=models.DateField(
                blank=True, null=True, verbose_name="password updated"
            ),
        ),
    ]
