# Generated by Django 3.0.5 on 2020-05-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_ipam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='ipaddress', name='organization'),
    ]
