# Generated by Django 3.1.1 on 2020-09-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0011_user_first_name_150_max_length'),
        ('openwisp_ipam', '0002_remove_ipaddress_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='openwisp_users.organization',
                verbose_name='organization',
            ),
        ),
    ]
