---
name: OpenWISP Ipam CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Python==${{ matrix.python-version }} | ${{ matrix.django-version }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - django~=3.2.0
          - django~=4.1.0
          - django~=4.2.0

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        id: deps
        run: |
          pip install -U pip wheel setuptools
          pip install -U -r requirements-test.txt
          pip install -U -e .
          pip install ${{ matrix.django-version }}
          sudo npm install -g jslint stylelint

      - name: QA checks
        run: ./run-qa-checks

      - name: Tests
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        run: |
          coverage run ./runtests.py --parallel
          SAMPLE_APP=1 coverage run ./runtests.py --parallel
          coverage combine

      - name: Upload Coverage
        if: ${{ success() }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: |
           python-${{ matrix.env.env }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Finish Coveralls
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
